# Generated by Django 5.2.1 on 2025-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
